### ISSUE TITLE
Why std::borrow::Borrow is not implemented for the collection types?

### ISSUE THREAD

**Issue by wada314** [fitzgen/bumpalo#107]
Hello, while I'm using the `Vec`s and `String`s of bumpalo, I realized that `std::borrow::Borrow` trait is not implemented for these types even though `std::convert::AsRef` is implemented.

I guessed the following state in [the `Borrow`'s document](https://doc.rust-lang.org/std/borrow/trait.Borrow.html) might be related, but as far as I checked the code the bumpalo's collections fulfill the condition:
> In particular `Eq`, `Ord` and `Hash` must be equivalent for borrowed and owned values: `x.borrow() == y.borrow()` should give the same result as `x == y`.

Does anyone know the reason why it is not implemented?
thanks,

**Comment by wada314** [comment]
My super random guess:
std library's `impl<T> Borrow<[T]> for Vec<T>` is defined in slice.rs, not in vec/mod.rs. Similar for `String`, it's defined in str.rs and not in string.rs.
Maybe forgot to copy these `impl`s when forking the implementations from the std library?

**Comment by fitzgen** [comment]
Yeah if it wasn't in `vec/mod.rs` then I probably missed it. Feel free to open a PR adding it!

**Comment by wada314** [comment]
Sure I will do it 👍 thank you! 😆
