### ISSUE TITLE
Clarify Bump is Send or not

### ISSUE THREAD

**Issue by stepancheg** [fitzgen/bumpalo#119]
* Rustdoc says [The `Bump` is `!Send`](https://github.com/fitzgen/bumpalo/blob/ce811a4f59b9a22ca9c362c40f1314763449b6ec/src/lib.rs#L157)
* But [`unsafe impl Send for Bump {}`](https://github.com/fitzgen/bumpalo/blob/ce811a4f59b9a22ca9c362c40f1314763449b6ec/src/lib.rs#L514)

**Comment by fitzgen** [comment]
See #118
