### ISSUE TITLE
Can `bumpalo::collections::vec::Vec` be `Send`?

### ISSUE THREAD

**Issue by haberman** [fitzgen/bumpalo#132]
Currently [`bumpalo::collections::vec::Vec` is not `Send`](https://docs.rs/bumpalo/2.2.2/bumpalo/collections/vec/struct.Vec.html#synthetic-implementations). Is there a reason for this?

I notice that [`std::vec::Vec` is `Send`](https://doc.rust-lang.org/beta/std/vec/struct.Vec.html#impl-Send). It seems like both the standard `Vec` and the bumpalo `Vec` will point at unaliased memory, so `Send` should be safe?

Digging a little deeper, I notice that `bumpalo::collections::RawVec` uses `NonNull<T>` for its pointer, whereas `std::vec::Vec` uses `Unique<T>`. Perhaps the bumpalo Vec could use `Unique<T>` also?

**Comment by fitzgen** [comment]
If it was send then bump would have to be sync (which it very much is not) since the vec holds a ref to the bump and will use it to realloc as needed when capacity gets filled and another item is being pushed

**Comment by fitzgen** [comment]
Note that std vec is only send when the A is send, which wouldn’t be true when A=&’a Bump

**Comment by haberman** [comment]
I forgot that the vec holds a ref to the bump.

I guess it could work if the bump was passed explicitly for all operations that can realloc? That would be a different type though.
