### ISSUE TITLE
Possible unexpected panic from Bump::alloc?

### ISSUE THREAD

**Issue by vorner** [fitzgen/bumpalo#15]
Hello

I was interested in how the thing is working inside, so I read the code. I discovered this thing: https://github.com/fitzgen/bumpalo/blob/master/src/lib.rs#L539.

Now, if I understand it correctly, this can panic „unexpectedly“, even if the user didn't do anything outright wrong.

* Let's say current chunk lives on really high address. For simplicity, let's say it simply lives in the highest page and the end has address 0xFFFFFFFE (so it's even, or something, let's say we are on 32bit).
* The chunk is running out of allocated space, so the finger is also somewhere very close.
* The user asks for allocation that has a sane size, but doesn't fit.

In this case, the address will overflow and panic will happen.

Would it make sense to not panic, but simply return None in that case, because the problem here is simply that the allocation doesn't fit into the current chunk and a new chunk needs to be created?

**Comment by fitzgen** [comment]
> Would it make sense to not panic, but simply return None in that case, because the problem here is simply that the allocation doesn't fit into the current chunk and a new chunk needs to be created?

That could work yeah.

**Comment by fitzgen** [comment]
Would you be interested in sending a PR?

**Comment by vorner** [comment]
Why not, here it goes.
