### ISSUE TITLE
`cargo miri test --features collections` fails

### ISSUE THREAD

**Issue by konsumlamm** [fitzgen/bumpalo#164]
Currently, the CI only runs Miri without any features enabled. When I tried to enable all features, I got an "Undefined Behavior" error, see https://github.com/fitzgen/bumpalo/runs/7022998455?check_suite_focus=true.

**Comment by fitzgen** [comment]
Not sure it is worth fixing this old forked `std` code. Would probably be better to either

* Update to new forked `std` code, which presumably has been fixed and runs green under MIRI, or
* wait for custom allocators to stabilize in `std` and delete the `collections` submodule.
