### ISSUE TITLE
`oom_instead_of_bump_pointer_overflow` test breakage on `nightly-2022-07-11`

### ISSUE THREAD

**Issue by Eliasin** [fitzgen/bumpalo#174]
The `oom_instead_of_bump_pointer_overflow` test fails on `nightly-2022-07-11` because of an [upstream change](https://github.com/rust-lang/rust/pull/95295) to `rustc` to restrict the size passed to `Layout::from_size_align` to be within `isize::MAX` instead of `usize::MAX`. Since this test uses `usize::MAX - p + 1` as a parameter to ensure overflow, this test now fails because of the call to `Layout::from_size_align` failing.

**Comment by Eliasin** [comment]
Changing
```rust
let size = usize::MAX - p + 1;
```
to
```rust
let size = (isize::MAX as usize) - p + 1;
```
gets the test to pass.
While I think due to the requirement that the panic be a `out of memory` panic specifically, this change should induce the correct test behavior but I'm not super sure what counts as overflow and whether or not `(isize::MAX as usize) - p + 1` would also guarantee overflow so I'll hold off on creating a PR for this.

**Comment by CAD97** [comment]
See also context in https://github.com/fitzgen/bumpalo/issues/128 the test seems to be a poor nondeterministic test to begin with.
