### ISSUE TITLE
MSRV build is broken

### ISSUE THREAD

**Issue by striezel** [fitzgen/bumpalo#195]
Currently, bumpalo does not build with its current MSRV 1.56.0 anymore, as can be seen here: https://github.com/fitzgen/bumpalo/actions/runs/4247510260/jobs/7385640541

> error: package `csv v1.2.0` cannot be built because it requires rustc 1.60 or newer, while the currently active rustc version is 1.56.0
Error: Process completed with exit code 101.

The `csv` crate changed its MSRV to 1.60 as part of the csv 1.2.0 release ([corresponding commit](https://github.com/BurntSushi/rust-csv/commit/521294f87b3e1e286829f85a34f397e007f081ed)).

So I guess the MSRV of `bumpalo` has to be increased, too.

**Comment by fitzgen** [comment]
This brings up an interesting question: should MSRV apply to being able to run tests/benchmarks (which pulls in dev deps like `csv`) or just to using the library itself (which does not)?

I guess the easiest thing to do is to bump the MSRV.

**Comment by striezel** [comment]
Trying to answer that question: Technically, just being able to build and use the library might be enough for most use cases. This would probably be acceptable to some users.

But then the CI should not run tests or benchmarks for the MSRV, and skipping tests means that one cannot really be sure that the library works as intended with the MSRV. So it is somewhat unclear, and bumping the MSRV is indeed the easiest thing to do.
