### ISSUE TITLE
Consider using the `allocator_api` crate

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/bumpalo#2]
Instead of forking from libstd directly ourselves.

This would involve merging `String` upstream into that crate plus any other collections we might end up needing.

**Comment by glandium** [comment]
Note that I'm open to having more collections in the `allocator_api`. I didn't come to it because I didn't need them yet.

**Comment by glandium** [comment]
Also note that the last published version is behind recent API changes to libstd, but I updated master recently.
