### ISSUE TITLE
MSRV disagrees between Cargo.toml and CHANGELOG.md

### ISSUE THREAD

**Issue by Wilfred** [fitzgen/bumpalo#238]
CHANGELOG states the the MSRV for 3.15 is 1.73, but Cargo.toml states 1.65. Which one is correct for bumpalo 3.15?

**Comment by fitzgen** [comment]
It is 1.73. Sorry, I forgot that you can state MSRV in `Cargo.toml` and that we do that here, so I forgot to update it. Will push a 3.15.1 point release and yank 3.15.0.
