### ISSUE TITLE
impl PartialEq for bumpalo::Vec<T>

### ISSUE THREAD

**Issue by jorendorff** [fitzgen/bumpalo#25]
I moved some data into bumpalo arenas. I had to change the struct definitions from using `std::vec::Vec` to `bumpalo::Vec`,  and as a result, I had to remove `#[derive(PartialEq)]` from those structs. Then I had to disable some tests that were using `assert_eq!`.

Suppose I implement these:

```
impl<'a, 'b, A, B> PartialEq<bumpalo::Vec<'b, B>> for bumpalo::Vec<'a, A>
where A: PartialEq<B> { ... }

impl<'a, 'b, A, B> PartialEq<&'b [b]> for bumpalo::Vec<'a, A>
where A: PartialEq<B> { ... }

impl<'a, 'b, A, B> PartialEq<&'b mut [b]> for bumpalo::Vec<'a, A>
where A: PartialEq<B> { ... }
```

Does that sound like a PR you'd take?

**Comment by jorendorff** [comment]
Oh, hmm. It looks like `std::vec::Vec` also has a few impls for fixed-size arrays, so I could add:

```
impl<'a, A, B> PartialEq<[B; $n]> for Vec<'a, A>
where A: PartialEq<B> { ... }

impl<'a, 'b, A, B> PartialEq<&'b [B; $n]> for Vec<'a, A>
where A: PartialEq<B> { ... }
```

...for each `$n` in `0..=32`.

**Comment by fitzgen** [comment]
Yeah, this would be great!

**Comment by jorendorff** [comment]
All of this is already implemented. I made a mistake somewhere.
