### ISSUE TITLE
Please consider relaxing the MSRV of this crate

### ISSUE THREAD

**Issue by notgull** [fitzgen/bumpalo#250]
Hello!

This crate is used as a dependency of a dependency of `wasm-bindgen`, which I use in many of my projects. This effectively sets `wasm-bindgen`'s MSRV to 1.73.0, even though [it is documented to be v1.57](https://github.com/rustwasm/wasm-bindgen/blob/fa6d2bc726813c9f5370f07c64a4b60f0ac1edd5/Cargo.toml#L15).

This poses an issue as I like to keep my crates pinned to MSRV version v1.63, as it is [the current version used by Debian Stable](https://packages.debian.org/stable/rustc) and it is needed in some environments for compliance reasons. So my only options is to pin bumpalo to v3.14.0, which is the last version that builds on Rust version v1.63. This *works* but requires special considerations that are annoying to accommodate.

Would it be at all possible to relax the MSRV of this crate to version 1.63.0 or lower? This would be greatly appreciated as it would enable me to use `bumpalo` on build systems dependent on Debian Stable. I empathize if this is not practical, but doing so would alleviate many headaches on my end.

Thank you!

**Comment by fitzgen** [comment]
Thanks for filing an issue.

As documented, we won't bump the MSRV for any patch version, but reserve the ability to do so in a minor version: https://github.com/fitzgen/bumpalo?tab=readme-ov-file#minimum-supported-rust-version-msrv

This provides a nice balance between stability and flexibility. Downstream users can avoid MSRV surprises while upstream isn't forced into stagnation.

I'd suggest sending a PR to `wasm-bindgen` changing the dep from `bumpalo = "3"` to `bumpalo = "3.10"` or whatever, as that will have the intended effect of sticking to a particular MSRV.
