### ISSUE TITLE
Appending to bumpalo::collections::Vec<'a, T> from regular Vec the most optimized way

### ISSUE THREAD

**Issue by kaphula** [fitzgen/bumpalo#254]
Hello, 

Is there a preferred way to append from regular `Vec<T>` to `bumpalo::collections::Vec<'a, T>` type?

For example, consider the following generic trait of vector that allows using both regular `Vec` and bumpalo `Vec`s which you can use with functions that you want to accept both types of vectors. If there is a better and more obvious way to achieve the same thing I am doing here, please let me know.
```rust 

pub trait VectorGeneric<T> {
    fn push(&mut self, v: T);
    fn clear(&mut self);
    fn pop(&mut self) -> Option<T>;

    #[inline]
    fn append_vec(&mut self, v: &mut Vec<T>);
}
pub type BumpVec<'a, T> = bumpalo::collections::Vec<'a, T>;

impl <T> VectorGeneric<T> for Vec<T> {
    fn push(&mut self, v: T) {
        self.push(v);
    }

    fn clear(&mut self) {
        self.clear();
    }

    fn pop(&mut self) -> Option<T> {
        self.pop()
    }

    fn append_vec(&mut self, v: &mut Vec<T>) {
        self.append(v);
    }
}



impl <T> VectorGeneric<T> for BumpVec<'_, T> {

    fn clear(&mut self) {
        self.clear();
    }

    fn push(&mut self, v: T) {
        self.push(v);
    }

    #[inline]
    fn append_vec(&mut self, v: &mut Vec<T>) {  
       // will compiler be smart enough to optimize this?
        for x in v.drain(..) {
            self.push(x)
        }
    }

    fn pop(&mut self) -> Option<T> {
        self.pop()
    }
}
```

Essentially since there is no native append on bumpalo `Vec` that accepts regular vectors and I am using traits as well, my question is will the compiler be smart enough to optimize the `append_vec` as if it were a regular `vec.append(&mut other_vec)` call. Any thoughts on this?

**Comment by fitzgen** [comment]
You probably want to use `extend_from_slice` or, if your type is `Copy`, you can use `extend_from_slice_copy`.

**Comment by kaphula** [comment]
That requires `T` to implement `Clone` which is not required with the current implementation, and even the regular `append` of  `Vec` does not clone but move. But I guess it is fine as it is in the code example, I tried to see how does the generated assembly look in godbolt and either version of `append_vec` seemed to be identical unless I missed something.
