### ISSUE TITLE
Is `Bump` thread-safe?

### ISSUE THREAD

**Issue by kckeiks** [fitzgen/bumpalo#258]
It would be helpful to document this.

**Comment by bluurryy** [comment]
The readme section [Thread Support](https://github.com/fitzgen/bumpalo?tab=readme-ov-file#thread-support) mentions that "`Bump` is `!Sync`" (`Bump` does not implement `Sync`) which means that it can't be shared among threads, aka not thread-safe.

**Comment by kckeiks** [comment]
> The readme section [Thread Support](https://github.com/fitzgen/bumpalo?tab=readme-ov-file#thread-support) mentions that "`Bump` is `!Sync`" (`Bump` does not implement `Sync`) which means that it can't be shared among threads, aka not thread-safe.

Yes, I noticed that, but if you wrap it in an `Arc` and, since it implements `Send`, it can be shared among threads. Therefore, it might be worth **explicitly** stating that it is not thread-safe.

**Comment by kckeiks** [comment]
> That's because that `Arc<T>` requires `T` to implement both `Sync + Send` for itself to implement `Sync` and `Send`.

Ah yes, I forgot about the `Sync` bound there. Thank you.

**Comment by fitzgen** [comment]
If anyone wants to submit a PR updating docs and making this stuff more clear, I'd be happy to review and merge :)
