### ISSUE TITLE
double size of chunk each time we hit the global allocator for a new chunk

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/bumpalo#3]
Within reason. Should probably have a max chunk size.

**Comment by Kerollmops** [comment]
Hey, I think I indeed hit the global allocator, bumpalo was trying to allocate 13GiB and the global allocator (jemalloc) refuses to do that, crashing the program.

It could indeed be a good thing to be able to set the maximum size of a chunk. Maybe be a parameter on the `Bump` type?

**Comment by fitzgen** [comment]
I think it would make sense to try doubling and if that doesn't succeed, then try the current chunk size again, and if that fails, then call the OOM handler.

If you'd like to make this PR, I would be happy to review it.
