### ISSUE TITLE
Provide an `alloc_extend` method

### ISSUE THREAD

**Issue by ennis** [fitzgen/bumpalo#4]
It would be great if `Bump` could provide an `alloc_extend` method to allocate values from an iterator and return a slice (similarly to [TypedArena::alloc_extend](https://docs.rs/typed-arena/1.4.1/typed_arena/struct.Arena.html#method.alloc_extend)). Something in the lines of:

```
pub fn alloc_extend<T, I>(&self, iterable: I) -> &mut [T] where
    T: BumpAllocSafe,
    I: IntoIterator<Item = T>, 
```

**Comment by fitzgen** [comment]
We have `alloc_slice_fill_iter` and various other `alloc_slice_*` methods now, so I think we can close this. If not, please open a new issue with specifics!
