### ISSUE TITLE
Provide a method to allocate a slice of zeroed/default values

### ISSUE THREAD

**Issue by ztlpn** [fitzgen/bumpalo#41]
Currently to bump-allocate any slice an existing slice is needed which is not always convenient. I guess currently the workaround is to use the `alloc_layout` method, but a method that doesn't require `unsafe` would be handy. Another handy addition would be a method that allocates and fills a slice with copies/clones of a single value.

**Comment by ztlpn** [comment]
@fitzgen I can do a PR if you think that this addition makes sense.

**Comment by fitzgen** [comment]
Can you sketch the API / method signature you're looking for here?

Zeroing memory is not going to result in a safe API in the general case (hence [`std::mem::zeroed`](https://doc.rust-lang.org/nightly/std/mem/fn.zeroed.html) being `unsafe`) so if your goal is avoiding `unsafe` I think we might need to workshop the API design a bit.

**Comment by ztlpn** [comment]
Something like
```rust
fn alloc_slice_fill_copy<T: Copy>(&self, len: usize, value: &T) -> &mut [T];
fn alloc_slice_fill_clone<T: Clone>(&self, len: usize, value: &T) -> &mut [T];
fn alloc_slice_fill_default<T: Default>(&self, len: usize) -> &mut [T];
```
Basically the equivalent of `vec![len; value]`.

> Zeroing memory is not going to result in a safe API in the general case

Yeah, I don't need zeroed memory in particular, but slice with default values. It was just that I had integer types in mind when I created the issue.

**Comment by fitzgen** [comment]
That looks great -- happy to take a PR implementing those APIs!

**Comment by fitzgen** [comment]
I believe this is fully implemted now. If I'm mistaken, please re-open!

**Comment by ztlpn** [comment]
Thanks! @fitzgen It would be great if you could cut a release with this feature!

**Comment by fitzgen** [comment]
See #51
