### ISSUE TITLE
Add an `into_bump_slice_mut` method for Vec?

### ISSUE THREAD

**Issue by TheDan64** [fitzgen/bumpalo#64]
If I understand correctly, two `Vec`s from the same `Bump` have separate allocations, correct? It seems like you should be able to consume them into distinct mutable slices, just like you can do currently do immutably with `into_bump_slice`.

**Comment by fitzgen** [comment]
This should be possible, yeah. Would you like to send a PR?

**Comment by TheDan64** [comment]
Sure! Thanks!
