### ISSUE TITLE
Add try_reserve/_exact methods for Vec?

### ISSUE THREAD

**Issue by TheDan64** [fitzgen/bumpalo#66]
I tried to add these try_* methods (since I need fallible allocation) to `Vec` by wrapping the `RawVec` methods of the same names. However, they still seem to be infallible due to the alloc impl always returning `Ok`? https://github.com/fitzgen/bumpalo/blob/master/src/lib.rs#L1076

Would it be possible to make them fallible?

**Comment by fitzgen** [comment]
Thanks for opening an issue. I'm open to the idea, but I still have some design questions I'm unsure about:

* Would you expect these methods to return an `Err` if the current chunk that we're bumping out of is full or only if the global allocator returns an error for getting a new chunk to bump out of?

* A variant for each? I.e. `try_alloc_in_current_chunk` and `try_alloc_in_new_chunk_if_necessary`?

Finally, are you interested in doing the implementation work?

**Comment by TheDan64** [comment]
Yeah, I'd be interested in implementation.

Personally, I'm only concerned about when the global allocator fails. However, if you think there's value in adding the other variant then we could do that too. Or at the very least keep the code open to adding that variant when someone does require it.

**Comment by fitzgen** [comment]
Ok, let's start with just the conservative approach of only when the global allocator fails :+1:
