### ISSUE TITLE
Implement `Sync` for `Vec`.

### ISSUE THREAD

**Issue by zakarumych** [fitzgen/bumpalo#72]
It seems that for `T: Sync` `Vec<'bump, T>`  should implement `Sync` as well.

**Comment by fitzgen** [comment]
I think you're correct. The bump arena is not sync, but `Vec<'bump, T>` won't touch the bump arena unless you have mutable access, which you can't across threads.

Are you interested in submitting a PR?

**Comment by zakarumych** [comment]
Returning to the issue.
There is a way to send `&Bump` to another thread is `Vec` would be `Sync`. So this would be unsound.
