### ISSUE TITLE
Layout::array has been stabilized

### ISSUE THREAD

**Issue by TethysSvensson** [fitzgen/bumpalo#77]
The function [`Layout::array`][array] has been stabilized.

This means that the TODO in [`lib.rs`][lib] can finally be fixed. The fix would mean that we will no longer have to do defensive coding in `layout_for_array`. I think this might also be a small reduction in the generated code size, but I haven't actually tested it.

However given that 1.44 has **just** been stabilized, now is probably not the time to begin depending on it. Do you think we should perhaps create a version policy for bumpalo?

[array]: https://doc.rust-lang.org/std/alloc/struct.Layout.html#method.array
[lib]: https://github.com/fitzgen/bumpalo/blob/bb1b1277fae63a814d1d62ad65303d17ccab25ee/src/lib.rs#L323

**Comment by fitzgen** [comment]
I'm happy to document the MSRV and feel free to bump it in `Y` versions in `X.Y.Z`.

**Comment by TethysSvensson** [comment]
In that case, I will do a PR which fixes the TODO and adds a note in the README about the MRSV.

I think it would probably also be helpful to test the MSRV as part of the CI workflow, though I don't understand that workflow well enough to update it myself.

**Comment by fitzgen** [comment]
Fixed in #79
