### ISSUE TITLE
Provide feature to use nightly allocator API

### ISSUE THREAD

**Issue by NOBLES5E** [fitzgen/bumpalo#87]
In latest Rust nightly we can allocate with custom allocator (for example https://doc.rust-lang.org/nightly/alloc/vec/struct.Vec.html#method.new_in).

It will be great for bumpalo to provide the ability to use this. To achieve this, the `&Bump` needs to implement `std::alloc::AllocRef`.

**Comment by fitzgen** [comment]
I am in favor of this, but I do not have time to implement it myself right now. Happy to review a PR.
